# Generated by Django 4.2.7 on 2025-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="디자이너 아이디"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="디자이너 패스워드"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="디자이너 이름")),
                (
                    "profile_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="designer_profiles/",
                        verbose_name="디자이너 프로필 사진",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        default="", max_length=50, verbose_name="디자이너 전화번호"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=100, verbose_name="디자이너 주소"
                    ),
                ),
            ],
            options={
                "verbose_name": "디자이너",
                "verbose_name_plural": "디자이너들",
                "db_table": "designer",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(max_length=50, unique=True, verbose_name="공장 아이디"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="공장 패스워드")),
                ("name", models.CharField(max_length=50, verbose_name="공장 이름")),
                (
                    "profile_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="factory_profiles/",
                        verbose_name="공장 프로필 사진",
                    ),
                ),
                (
                    "contact",
                    models.CharField(default="", max_length=50, verbose_name="공장 전화번호"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=100, verbose_name="공장 주소"),
                ),
            ],
            options={
                "verbose_name": "공장",
                "verbose_name_plural": "공장들",
                "db_table": "factory",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(default="", max_length=20)),
                ("contact", models.CharField(default="", max_length=20)),
                ("address", models.TextField(default="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
            },
        ),
    ]
