# Generated by Django 4.2.7 on 2025-08-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_designer_factory_remove_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="portfolio_url",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="specialization",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="user",
        ),
        migrations.AddField(
            model_name="designer",
            name="address",
            field=models.CharField(default="", max_length=100, verbose_name="디자이너 주소"),
        ),
        migrations.AddField(
            model_name="designer",
            name="contact",
            field=models.CharField(default="", max_length=50, verbose_name="디자이너 전화번호"),
        ),
        migrations.AddField(
            model_name="designer",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="디자이너 이름"),
        ),
        migrations.AddField(
            model_name="designer",
            name="password",
            field=models.CharField(default="", max_length=50, verbose_name="디자이너 패스워드"),
        ),
        migrations.AddField(
            model_name="designer",
            name="profile_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="designer_profiles/",
                verbose_name="디자이너 프로필 사진",
            ),
        ),
        migrations.AddField(
            model_name="designer",
            name="user_id",
            field=models.CharField(default="", max_length=50, verbose_name="디자이너 아이디"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
