# Generated by Django 4.2.7 on 2025-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_designer_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factory",
            name="business_license",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="production_capacity",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="user",
        ),
        migrations.AddField(
            model_name="factory",
            name="address",
            field=models.CharField(default="", max_length=100, verbose_name="공장 주소"),
        ),
        migrations.AddField(
            model_name="factory",
            name="contact",
            field=models.CharField(default="", max_length=50, verbose_name="공장 전화번호"),
        ),
        migrations.AddField(
            model_name="factory",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="공장 이름"),
        ),
        migrations.AddField(
            model_name="factory",
            name="password",
            field=models.CharField(default="", max_length=128, verbose_name="공장 패스워드"),
        ),
        migrations.AddField(
            model_name="factory",
            name="profile_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="factory_profiles/",
                verbose_name="공장 프로필 사진",
            ),
        ),
        migrations.AddField(
            model_name="factory",
            name="user_id",
            field=models.CharField(default="", max_length=50, verbose_name="공장 아이디"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="password",
            field=models.CharField(
                default="", max_length=128, verbose_name="디자이너 패스워드"
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
