# Generated by Django 4.2.7 on 2025-08-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_factory_business_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="name",
            field=models.CharField(max_length=50, verbose_name="디자이너 이름"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="password",
            field=models.CharField(max_length=128, verbose_name="디자이너 패스워드"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="user_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="디자이너 아이디"),
        ),
        migrations.AlterField(
            model_name="factory",
            name="name",
            field=models.CharField(max_length=50, verbose_name="공장 이름"),
        ),
        migrations.AlterField(
            model_name="factory",
            name="password",
            field=models.CharField(max_length=128, verbose_name="공장 패스워드"),
        ),
        migrations.AlterField(
            model_name="factory",
            name="user_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="공장 아이디"),
        ),
    ]
