# Generated by Django 4.2.7 on 2025-08-18 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="주문 번호"
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문들",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="RequestOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designer_name",
                    models.CharField(max_length=20, verbose_name="디자이너 사용자 이름"),
                ),
                ("product_name", models.CharField(max_length=100, verbose_name="제품명")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="수량",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="납기일")),
                (
                    "work_sheet_path",
                    models.FileField(
                        upload_to="request_orders/worksheets/", verbose_name="작업지시서"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "매칭 대기중"),
                            ("matched", "매칭 완료"),
                            ("cancelled", "취소됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="매칭 상태",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_orders",
                        to="manufacturing.order",
                        verbose_name="주문 번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 요청",
                "verbose_name_plural": "주문 요청들",
                "db_table": "request_order",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="제품명")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "봄"),
                            ("summer", "여름"),
                            ("autumn", "가을"),
                            ("winter", "겨울"),
                            ("all-season", "사계절"),
                        ],
                        max_length=20,
                        verbose_name="시즌",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("teens", "10대"),
                            ("twenties", "20대"),
                            ("thirties", "30대"),
                            ("forties", "40대"),
                            ("fifties-plus", "50대 이상"),
                            ("all-ages", "전 연령"),
                        ],
                        max_length=20,
                        verbose_name="타겟 고객층",
                    ),
                ),
                ("concept", models.TextField(verbose_name="컨셉 설명")),
                (
                    "image_path",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="design_image/",
                        verbose_name="디자인 이미지",
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="포인트 부위 설명"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사이즈"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="수량",
                    ),
                ),
                (
                    "fabric",
                    models.JSONField(
                        blank=True,
                        help_text="원단 종류, 무게, 신축성 등의 정보를 JSON 형태로 저장",
                        null=True,
                        verbose_name="원단 정보",
                    ),
                ),
                (
                    "material",
                    models.JSONField(
                        blank=True,
                        help_text="단추, 지퍼, 라이닝 등의 정보를 JSON 형태로 저장",
                        null=True,
                        verbose_name="부자재 정보",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="납기일"),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "work_sheet_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="worksheets/",
                        verbose_name="작업지시서",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="accounts.designer",
                        verbose_name="디자이너",
                    ),
                ),
            ],
            options={
                "verbose_name": "제품",
                "verbose_name_plural": "제품들",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="manufacturing.product",
                verbose_name="제품",
            ),
        ),
        migrations.CreateModel(
            name="BidFactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_price",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="장당 가격",
                    ),
                ),
                ("expect_work_day", models.DateField(verbose_name="예상 납기일")),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("confirmed", "확인됨"),
                            ("completed", "완료"),
                            ("cancelled", "취소됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="주문 상태",
                    ),
                ),
                (
                    "is_matched",
                    models.BooleanField(default=False, verbose_name="낙찰 상태"),
                ),
                (
                    "matched_date",
                    models.DateField(blank=True, null=True, verbose_name="낙찰 일자"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="accounts.factory",
                        verbose_name="공장 ID",
                    ),
                ),
                (
                    "request_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="manufacturing.requestorder",
                        verbose_name="주문 번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "공장 입찰",
                "verbose_name_plural": "공장 입찰들",
                "db_table": "bid_factory",
                "unique_together": {("factory", "request_order")},
            },
        ),
    ]
