# Generated by Django 4.2.7 on 2025-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.ImageField(default='products/default.jpg', upload_to='design_image/'),
            preserve_default=False,
        ),
    ]
