# Generated by Django 4.2.7 on 2025-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='design_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', '봄'), ('summer', '여름'), ('autumn', '가을'), ('winter', '겨울'), ('all-season', '사계절')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_customer',
            field=models.CharField(choices=[('teens', '10대'), ('twenties', '20대'), ('thirties', '30대'), ('forties', '40대'), ('fifties-plus', '50대 이상'), ('all-ages', '전 연령')], max_length=20),
        ),
    ]
