# Generated by Django 4.2.7 on 2025-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0003_product_detail_alter_product_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("Free Size", "Free Size"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
