# Generated by Django 4.2.7 on 2025-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_product_detail_alter_product_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
