# Generated by Django 4.2.7 on 2025-08-04 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0004_product_fabric_product_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='주문 번호')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('confirmed', '확인됨'), ('in_production', '생산중'), ('completed', '완료'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='주문 수량')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='단가')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='총 금액')),
                ('receipt_path', models.FileField(blank=True, null=True, upload_to='orders/receipts/', verbose_name='영수증')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='주문 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '제품', 'verbose_name_plural': '제품들'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_customer',
        ),
        migrations.AddField(
            model_name='product',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='납기일'),
        ),
        migrations.AddField(
            model_name='product',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사이즈'),
        ),
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.CharField(choices=[('teens', '10대'), ('twenties', '20대'), ('thirties', '30대'), ('forties', '40대'), ('fifties-plus', '50대 이상'), ('all-ages', '전 연령')], default='all-ages', max_length=20, verbose_name='타겟 고객층'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='work_sheet_path',
            field=models.FileField(blank=True, null=True, upload_to='worksheets/', verbose_name='작업지시서'),
        ),
        migrations.AlterField(
            model_name='product',
            name='concept',
            field=models.TextField(verbose_name='컨셉 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'designer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='디자이너'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='포인트 부위 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.JSONField(blank=True, help_text='원단 종류, 무게, 신축성 등의 정보를 JSON 형태로 저장', null=True, verbose_name='원단 정보'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(upload_to='design_image/', verbose_name='디자인 이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.JSONField(blank=True, help_text='단추, 지퍼, 라이닝 등의 정보를 JSON 형태로 저장', null=True, verbose_name='부자재 정보'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', '봄'), ('summer', '여름'), ('autumn', '가을'), ('winter', '겨울'), ('all-season', '사계절')], max_length=20, verbose_name='시즌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='manufacturing.product', verbose_name='제품'),
        ),
    ]
