# Generated by Django 4.2.7 on 2025-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_order_customer_contact_order_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='product',
            name='composite_image',
            field=models.ImageField(blank=True, null=True, upload_to='composite_images/', verbose_name='합성 디자인 미리보기'),
        ),
    ]
